//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KotobuApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string Description { get; set; }
        public string CC { get; set; }
        public string CcDescription { get; set; }
        public string MainLink { get; set; }
        public string TwitterLink { get; set; }
        public string IgLink { get; set; }
        public string Categorys { get; set; }
        public string Cover { get; set; }
    }
}
